# Generated by Django 3.1.2 on 2020-11-02 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Código Solicitud')),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'SolicitudProducto',
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitudProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, verbose_name='cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('solicitud_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.solicitudproducto')),
            ],
            options={
                'db_table': 'DetalleSolicitudProd',
            },
        ),
    ]
