# Generated by Django 3.1.2 on 2020-11-23 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_detallesolicitudprod_solicitudproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='gramaje',
            field=models.CharField(choices=[('ml', 'ML'), ('gr', 'Gr'), ('unidad', 'Unidad')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('fruta', 'Fruta'), ('verdura', 'Verdura'), ('pastas', 'Pastas'), ('bebidas', 'Bebidas'), ('bebidas Alcoholicas', 'Bebidas Alcoholicas'), ('utensilio', 'Utensilio'), ('carnes rojas', 'Carnes Rojas'), ('carnes blancas', 'Carnes Blancas'), ('arroz', 'Arroz'), ('postre', 'Postre'), ('lacteo', 'Lacteos'), ('pan', 'Pan'), ('condimento', 'Condimento'), ('bebedas', 'Bebidas')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudproducto',
            name='fecha_solicitud',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
