# Generated by Django 3.1.2 on 2020-11-04 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_persona', models.IntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'DISPONIBLE'), ('ocupada', 'OCUPADA')], max_length=30, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'db_table': 'Mesa',
            },
        ),
    ]
