# Generated by Django 3.1.2 on 2020-11-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='precio',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='precio'),
        ),
    ]
