# Generated by Django 3.1.2 on 2020-11-09 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0002_receta_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='imagen',
        ),
    ]
