# Generated by Django 3.1.2 on 2020-11-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0003_remove_receta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='tipo',
            field=models.CharField(choices=[('postre', 'Postre'), ('bebida', 'Bebida'), ('plato', 'Plato')], max_length=30, null=True),
        ),
    ]
